### ISSUE TITLE
Does the type decorator works?

### ISSUE THREAD

**Issue by AdrySky** [XpressAI/xpipes#91]
**Reference** 
#86 

I feel like the `type` decorator doesn't change the type when we specify the type with the `type` keyword in the `xai_decorator`. Here why I said that.

Each `type` will have different InArgs and OutArgs by default as shown [here](https://github.com/XpressAI/xpipes/blob/master/src/components/xpipeBodyWidget.tsx#L1498-L1650). We can see how the `type` was set in the [GENERAL category](https://github.com/XpressAI/xpipes/blob/master/xpipes/handlers/components.py#L24-L40). 

Assuming changing the `type` using the decorator, that component should be by default have the correct `InArgs` and `OutArgs`. 
For example, if I did something like this in the script :
```
@xai_component(type="math")
class NewMath(Component):

    def __init__(self):

        self.done = False

    def execute(self) -> None:
        
        self.done = True
```

**Expected Result**(should be the same as Math Operation's component):
![Newmath expected](https://user-images.githubusercontent.com/84708008/150310828-559a40ac-f25c-44bd-a16d-91fabdf5a645.PNG)
![math](https://user-images.githubusercontent.com/84708008/150311953-3bf673ef-657f-4e2a-93cc-49341267eabf.PNG)

**Actual Result:**
![Newmath Actual](https://user-images.githubusercontent.com/84708008/150311591-aa172fd9-e2a8-44ee-928d-9c0c86ba787a.PNG)

I could be wrong in expecting that result since I assumed `type` works like that.

**Comment by treo** [comment]
It works as related to having that type on the component itself. 

Components that are defined as components aren't in the `GENERAL` category though. 

If it only ever affects those in `GENERAL`, then it didn't do anything before either 😂

**Comment by AdrySky** [comment]
I see. I was hoping it could affects those **not** in `GENERAL` though.

**Comment by treo** [comment]
It does the same thing as before, which is "put a type value on the component that is returned". 

As far as I can tell, that value only really changes something for components in the `GENERAL` category, but we were still putting them on a few components in the `ADVANCED` category. 

I didn't dive into the code that is processing the type value, but if we actually want it to do something we can add that. However, that wasn't the point of the referenced pull request. The point of the pull request was simply to get rid of some hard coded values that where detached from the components they were referring to.

**Comment by AdrySky** [comment]
> The point of the pull request was simply to get rid of some hard coded values that where detached from the components they were referring to.

Yeah, my bad. I assumed that pull request can do the impossible or non-existing things. 

Also, I'll close this issue as you already answered my question.
